[package]
name = "tlbb_token"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"  # Ensure this matches your Anchor CLI version

[features]
idl-build = ["anchor-lang/idl-build"]
anchor-debug = ["anchor-lang/anchor-debug"]