[programs.localnet]
tlbb_token = "Euueq2HBsDG4Dwf1QtHRrXCSnmdUQmBXJHqfsWDhYYX1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"