name: Build and Deploy TLBB Token Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ANCHOR_WALLET: ${{ secrets.ANCHOR_WALLET }}
      ANCHOR_PROVIDER_URL: ${{ secrets.ANCHOR_PROVIDER_URL }}
      TLBB_PROGRAM_ID: ${{ secrets.TLBB_PROGRAM_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Solana CLI
        run: |
          curl -sSfL https://release.solana.com/stable/install | sh
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli

      - name: Configure Wallet
        run: |
          mkdir -p ~/.config/solana
          echo "${{ secrets.ANCHOR_WALLET }}" > ~/.config/solana/id.json
          solana config set --url ${{ secrets.ANCHOR_PROVIDER_URL }}

      - name: Build the Program
        run: anchor build

      - name: Deploy the Program
        run: anchor deploy