name: Build and Deploy TLBB Token Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ANCHOR_WALLET: ${{ secrets.ANCHOR_WALLET }}
      ANCHOR_PROVIDER_URL: ${{ secrets.ANCHOR_PROVIDER_URL }}
      TLBB_PROGRAM_ID: ${{ secrets.TLBB_PROGRAM_ID }}

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Solana CLI
      - name: Install Solana CLI
        run: |
          curl -sSfL https://release.solana.com/stable/install | sh
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      # Step 3: Install Rust and Anchor
      - name: Install Rust and Anchor
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli

      # Step 4: Configure Solana Wallet
      - name: Configure Solana Wallet
        run: |
          mkdir -p ~/.config/solana
          echo "${{ secrets.ANCHOR_WALLET }}" > ~/.config/solana/id.json

      # Step 5: Build the Program
      - name: Build the Program
        run: |
          anchor build

      # Step 6: Deploy the Program
      - name: Deploy the Program
        run: |
          anchor deploy
